FROM debian:12
LABEL maintainer="email@email.com"
ENV GLPI_VERSION 10.0.17
ENV LAST_RELEASE 10.0.17

ENV PATH="/opt/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

RUN apt update
RUN apt-get install php-zip
RUN apt-get install php-bz2
RUN apt update && apt install tzdata -y \
	&&  echo "America/Belem" > /etc/timezone \
	&& dpkg-reconfigure -f noninteractive tzdata \
	&&  apt  install -y \
	php \
	php-xml \
	php-opcache \
	php-apcu \
	php-bcmath \
	php-imap \
	php-cas \
	php-soap \
	php-cli \
	php-common \
	php-snmp \
	php-xmlrpc \
	php-gd \
	php-ldap \
	libapache2-mod-php \
	php-curl \
	php-mbstring \
	php-mysql \
	php-dev \
	php-pear \
	php-intl \
	libbz2-dev \
	zlib1g-dev \
	apache2 \
	unzip \
	curl \
	snmp \
	nano \
	wget \ 
	cron && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* 

RUN docker-php-ext-install bz2
RUN docker-php-ext-install zip

RUN printf '<VirtualHost *:80>\n \
	DocumentRoot /var/www/html/glpi\n \
	<Directory /var/www/html/glpi>\n \
	AllowOverride All\n \
	Order Allow,Deny\n \
	Allow from all\n \
	</Directory>\n \
	ErrorLog /var/log/apache2/error-glpi.log\n\
	LogLevel warn\n \
	CustomLog /var/log/apache2/access-glpi.log combined\n \
</VirtualHost> '\
>> /etc/apache2/conf-available/glpi.conf 

RUN printf '<Directory /var/www/html/glpi/public>\n \
        Options Indexes FollowSymLinks\n \
        AllowOverride None\n \
        Require all granted\n \
</Directory>' \
>> /etc/apache2/conf-available/glpi2.conf

RUN	a2enconf glpi.conf \
	&& a2enconf glpi2.conf \
	&& echo "*/5 * * * * /usr/bin/php /var/www/html/glpi/front/cron.php &>/dev/null"  > /var/spool/cron/crontabs/root \
	&& echo ' \n#!/bin/bash \n/etc/init.d/apache2 start \n/bin/bash' > /usr/bin/glpi \
	&& chmod +x /usr/bin/glpi

EXPOSE 80

ADD https://github.com/glpi-project/glpi/releases/download/$LAST_RELEASE/glpi-$GLPI_VERSION.tgz ./
RUN tar -xzf  glpi-$GLPI_VERSION.tgz -C /var/www/html  \
	&& chmod 775 -Rf /var/www/html/glpi \
	&& chown www-data. -Rf /var/www/html/glpi  \
	&& rm -rf   glpi-$GLPI_VERSION.tgz

CMD /usr/bin/glpi
 
CMD ["-D", "FOREGROUND"]
ENTRYPOINT ["apachectl"]
