# Usar a imagem Debian 12 como base
FROM debian:12

# Instalar dependências necessárias
RUN apt-get update && \
    apt-get install -y apache2 libapache2-mod-php php php-mysql php-curl php-gd php-mbstring php-xml php-ldap php-imap php-apcu php-xmlrpc php-cas php-intl php-zip php-bz2 php-json php-ldap wget unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Baixar e descompactar o GLPI
RUN wget https://github.com/glpi-project/glpi/releases/download/10.0.15/glpi-10.0.15.tgz && \
    tar -xzf glpi-10.0.15.tgz && \
    mv glpi /var/www/html/glpi && \
    mv /var/www/html/glpi/files /var/lib/glpi && \
    chown -R www-data:www-data /var/www/html/glpi /var/lib/glpi && \
    chmod -R 755 /var/www/html/glpi /var/lib/glpi

# Configurar o Apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
COPY glpi-apache-config.conf /etc/apache2/sites-available/000-default.conf

# Ativar o módulo rewrite do Apache
RUN a2enmod rewrite

# Configurar PHP para definir session.cookie_httponly como On
RUN echo "session.cookie_httponly = On" >> /etc/php/$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;')/apache2/php.ini

# Expor a porta 80
EXPOSE 80

# Definir o ponto de entrada
CMD ["apachectl", "-D", "FOREGROUND"]
